title:              Voyage
email:              v5chauha.uwaterloo@gmail.com
description:        Sometimes cool other times geeky stuff
author:             Vivek Chauhan
baseurl:            ""
url:                "https://chauhan-vivek.github.io"

# Social Profiles
twitter_username:   
github_username:  chauhan-vivek
facebook_username:  
instagram_username:  
linkedin_username: v5chauhan

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
